namespace EducationalCenter.Shared.DTOs;

// Used when returning a student to the user (includes the ID generated by the DB)
public record StudentResponseDto(
    int Id, 
    string FirstName, 
    string LastName, 
    string Email, 
    string PhoneNumber);

// Used when the user is creating a new student (ID is not needed)
public record CreateStudentRequestDto(
    string FirstName, 
    string LastName, 
    string Email, 
    string PhoneNumber);
    